// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXF7WlxanVUWCM26iFp4YaK1utRXliHvU',
    appId: '1:663597272912:web:e8f70253ffa24034946655',
    messagingSenderId: '663597272912',
    projectId: 'auth-project-e3ff7',
    authDomain: 'auth-project-e3ff7.firebaseapp.com',
    storageBucket: 'auth-project-e3ff7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCekpWARlelKZfJ3wqyCL-YFdDE0vEoZAE',
    appId: '1:663597272912:android:fa67e71dfd42da97946655',
    messagingSenderId: '663597272912',
    projectId: 'auth-project-e3ff7',
    storageBucket: 'auth-project-e3ff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvLSLTpUK8JhMh8qiEXWatClaMiewWTUs',
    appId: '1:663597272912:ios:171a96c116c5c4d5946655',
    messagingSenderId: '663597272912',
    projectId: 'auth-project-e3ff7',
    storageBucket: 'auth-project-e3ff7.appspot.com',
    iosBundleId: 'com.example.authUsingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvLSLTpUK8JhMh8qiEXWatClaMiewWTUs',
    appId: '1:663597272912:ios:43fcd1ff36fec436946655',
    messagingSenderId: '663597272912',
    projectId: 'auth-project-e3ff7',
    storageBucket: 'auth-project-e3ff7.appspot.com',
    iosBundleId: 'com.example.authUsingFirebase.RunnerTests',
  );
}
